# Generated by Django 4.2.16 on 2024-10-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
